# Generated by Django 4.2.21 on 2025-05-19 03:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.TimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('check_in', 'Entrada'), ('check_out', 'Salida')], max_length=10)),
                ('is_late', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de llegada')),
                ('end_time', models.TimeField(verbose_name='Hora de salida')),
                ('is_active', models.BooleanField(default=True, verbose_name='Día hábil')),
            ],
            options={
                'ordering': ['user', 'day_of_week'],
            },
        ),
    ]
